version: '3.7'
services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      
  db:
    image: postgres
    environment: 
      POSTGRES_USER: admin
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: password
    volumes:
      - ~/pgdata:/var/lib/postgresql/data

volumes:
  static:
  pgdata:
